### ISSUE TITLE
VespAI Submodule Clone Error: "fatal: remote error: upload-pack: not our ref"

### ISSUE THREAD

**Issue by marcory-hub** [andrw3000/vespai#1]
I'm encountering an error while setting up VespAI on a Raspberry Pi 4 8 GB, OS Ubuntu 22.04.4 following the instructions. During the git clone command with the --recursive flag for the VespAI repository, with `git clone https://github.com/andrw3000/vespai --recursive` I get the following error:

> fatal: remote error: upload-pack: not our ref e8b8074e93ec7e39417364ae23581b3fb64a9b18
> fatal: Fetched in submodule path 'explanation/lrp-resnet', but it did not contain e8b8074e93ec7e39417364ae23581b3fb64a9b18. Direct fetching of that commit failed.

Steps done so far:
- retried the cloning process multiple times (also in a venv)
- attempted to reinitialize all submodules using git submodule update --init --recursive.
- tried removing the problematic submodule from the git index using git submodule deinit -f explanation/lrp-resnet and then re-adding it with git submodule add https://github.com/dmitrysarov/LRP_decomposition explanation/lrp-resnet.
- explicitly cloned the problematic submodule using git clone https://github.com/dmitrysarov/LRP_decomposition explanation/lrp-resnet.
Unfortunately, none of these steps resolved the issue.

Title: VespAI Submodule Clone Error: "fatal: remote error: upload-pack: not our ref"
Description
I'm encountering an error while setting up VespAI on a Raspberry Pi 4 following the instructions (link to instructions, if available). During the git clone command with the --recursive flag for the VespAI repository, I get the following error:

fatal: remote error: upload-pack: not our ref e8b8074e93ec7e39417364ae23581b3fb64a9b18
fatal: Fetched in submodule path 'explanation/lrp-resnet', but it did not contain e8b8074e93ec7e39417364ae23581b3fb64a9b18. Direct fetching of that commit failed.
Troubleshooting Steps Taken:

I have verified that sudo apt install -y git is successful, and git is the latest version.
I have retried the cloning process multiple times.
I have attempted to reinitialize all submodules using git submodule update --init --recursive.
I have tried removing the problematic submodule from the git index using git submodule deinit -f explanation/lrp-resnet and then re-adding it with git submodule add https://github.com/dmitrysarov/LRP_decomposition explanation/lrp-resnet.
I have explicitly cloned the problematic submodule using git clone https://github.com/dmitrysarov/LRP_decomposition explanation/lrp-resnet.
Unfortunately, none of these steps resolved the issue.

I suspect the error might be due to a deleted or moved commit on the remote repository (https://github.com/andrw3000/vespai) for the submodule explanation/lrp-resnet.

Could you please confirm if the commit e8b8074e93ec7e39417364ae23581b3fb64a9b18 is no longer available in the explanation/lrp-resnet submodule?
If so, are there any alternative branches or solutions to proceed with the VespAI installation?
Any other suggestions to troubleshoot this cloning issue would be greatly appreciated.

**Comment by andrw3000** [comment]
Hello, this submodule relates to a specified use case (applying LRP analysis to the model). I will check the dependency as this was included some time ago. In the meantime, if you clone the model without the `--recursive` flag you should be able to use the core functionality (the YOLOv5 model). Note that the trained parameter files are not included. Please confer with @Toshea111 regarding these.

**Comment by marcory-hub** [comment]
Thanks! Cloning without the --recursive flag resolved the initial issue. (now new problems related to camera support on Ubuntu keep me buzzy). I'll reach out to @Toshea111 as suggested to address the missing parameter files.

**Comment by Toshea111** [comment]
Hello @marcory-hub,

A brief question about your camera, what model are you using?

From testing, any of the CSI-based Pi cameras will struggle to work, although most USB-based models will be compatible.

**Comment by marcory-hub** [comment]
Hello @Toshea111 ,

Thanks, I'm using a pi model 3 CSI-based camera (and tried a 16MP AF Camera Auto Focus IMX519-78, also CSI-based). I've encountered numerous online reports of similar issues. So, I will switch to a USB-model.

**Comment by wombat70** [comment]
You may be interested in PR #3 - it contains an Ansible playbook which also deals with the submodule issue.

**Comment by stephenpcook** [comment]
I solved this in stephenpcook/vespai@70dabecaa6ce408c2f71821cfbc6ad77f0cdfea9 by updating the submodule from the missing commit `e8b807` to the currently available head (dmitrysarov/LRP_decomposition@72031a5252aafb7f7e51abe28bba40dba0fce9e7).
