### ISSUE TITLE
Is it possible to add jersey.mp4 to the repo for initial testing of installation?

### ISSUE THREAD

**Issue by wombat70** [andrw3000/vespai#2]
Hi. I'm just getting my RPi4 software configured, based on the instructions in the current [`setup-from-git-repo.pdf`](https://github.com/andrw3000/vespai/blob/786c394a8835cc2850ec3a462a8aaaf2e8520172/manuals/setup-from-git-repo/setup-from-git-repo.pdf)

Section 7 "Run Monitor" of this doc references a file `jersey.mp4`, which I assume is a video file for testing of the monitor application.

Is it possible to add this or similar video file to the repo? _I couldn't find it._

Thanks!

Tom

**Comment by andrw3000** [comment]
@Toshea111 Assigning Thomas to this one, who owns the rights to the data.

**Comment by Toshea111** [comment]
@wombat70 No problem, I have now added 'Jersey.mp4' to the following path:

[manuals/test/Jersey.mp4](https://github.com/andrw3000/vespai/blob/57eb2ee8f8a157603fd7e90135735294985c883a/manuals/test/Jersey.mp4)

Let me know if you would prefer a different location.

**Comment by wombat70** [comment]
Thank you! Location is absolutely fine.
